"""
Data access layer for the Streamlit UI.

This module is a thin adapter over the existing backend. It:
  - triggers the existing `app.workflow.run_workflow()` to execute a run
  - loads the raw referrals (for display context such as summary/source)
  - reads the artifacts the backend already writes (audit trace,
    case packages, triage notes) as the source of truth

It contains NO policy evaluation, NO triage-note generation, and NO
referral-status logic. All decisions come from the backend.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

ARTIFACTS_DIR = REPO_ROOT / "artifacts"
LATEST_RUN_JSON = ARTIFACTS_DIR / "latest-run.json"
LATEST_RUN_MD = ARTIFACTS_DIR / "latest-run.md"
TRIAGE_NOTES_DIR = ARTIFACTS_DIR / "triage-notes"
CASES_DIR = ARTIFACTS_DIR / "cases"


@dataclass
class ReferralView:
    """
    A display-friendly, read-only merge of one Referral and its
    corresponding AgentResult. Every field is copied verbatim from
    the backend's own data structures - nothing here is inferred
    or recomputed.
    """

    referral_id: str
    resident_ref: str
    status: str
    requested_action: str
    reason: str
    action_taken: str
    source: str
    summary: str
    urgency: str
    received_at: str
    relevant_history: list[dict[str, Any]]
    missing_information: list[str]
    escalation_package: dict[str, Any] | None
    handoff_package: dict[str, Any] | None
    triage_note: str | None
    triage_note_provider: str | None
    triage_note_generated_by: str | None


def run_backend_workflow():
    """
    Execute the real backend workflow end to end.

    Returns whatever `app.workflow.run_workflow()` returns
    (a list[AgentResult]). This function performs no policy logic
    itself - it is a direct passthrough.
    """
    from app.workflow import run_workflow

    return run_workflow()


def load_raw_referrals() -> dict[str, Any]:
    """Load the original referral queue, keyed by referral_id, for
    display context only (summary, source, urgency, received_at)."""
    from app.referrals import load_referrals

    referrals = load_referrals()
    return {r.referral_id: r for r in referrals}


def _history_events_to_dicts(events) -> list[dict[str, Any]]:
    out = []
    for event in events:
        if isinstance(event, dict):
            out.append(event)
        else:
            out.append(
                {"date": event.date, "type": event.type, "detail": event.detail}
            )
    return out


def _read_triage_note_file(referral_id: str) -> tuple[str | None, str | None]:
    """
    Parse provider / generated_by out of the triage-note markdown file
    already written by app.triage_note.save_triage_note(). We only
    read what the backend already wrote - we do not regenerate it.
    """
    path = TRIAGE_NOTES_DIR / f"{referral_id}.md"

    if not path.exists():
        return None, None

    text = path.read_text(encoding="utf-8")

    generated_by_match = re.search(r"\*\*Generated by:\*\*\s*(.+)", text)
    provider_match = re.search(r"\*\*Provider:\*\*\s*(.+)", text)

    generated_by = generated_by_match.group(1).strip() if generated_by_match else None
    provider = provider_match.group(1).strip() if provider_match else None

    return provider, generated_by


def build_referral_views(results) -> list[ReferralView]:
    """
    Merge AgentResult objects (from the backend) with the original
    Referral records (for display context only) into ReferralView
    rows for the UI. No status/decision fields are recomputed.
    """
    raw_referrals = load_raw_referrals()
    views: list[ReferralView] = []

    for result in results:
        referral = raw_referrals.get(result.referral_id)

        provider, generated_by = (None, None)
        if getattr(result, "triage_note", None):
            provider, generated_by = _read_triage_note_file(result.referral_id)

        views.append(
            ReferralView(
                referral_id=result.referral_id,
                resident_ref=result.resident_ref,
                status=result.status.value
                if hasattr(result.status, "value")
                else str(result.status),
                requested_action=result.intent,
                reason=result.reason,
                action_taken=result.action_taken,
                source=referral.source if referral else "—",
                summary=referral.summary if referral else "—",
                urgency=referral.urgency if referral else "—",
                received_at=referral.received_at if referral else "—",
                relevant_history=_history_events_to_dicts(result.relevant_history),
                missing_information=list(result.missing_information or []),
                escalation_package=result.escalation_package,
                handoff_package=result.handoff_package,
                triage_note=result.triage_note,
                triage_note_provider=provider,
                triage_note_generated_by=generated_by,
            )
        )

    return views


def load_latest_trace() -> list[dict[str, Any]]:
    """Load the full audit trace already persisted by AuditLogger."""
    if not LATEST_RUN_JSON.exists():
        return []

    try:
        data = json.loads(LATEST_RUN_JSON.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []

    if not isinstance(data, list):
        return []

    return data


def load_latest_trace_markdown() -> str | None:
    if not LATEST_RUN_MD.exists():
        return None
    return LATEST_RUN_MD.read_text(encoding="utf-8")


def trace_for_referral(referral_id: str) -> list[dict[str, Any]]:
    """Filter the persisted audit trace down to one referral's events."""
    events = load_latest_trace()
    return [
        e
        for e in events
        if e.get("data", {}).get("referral_id") == referral_id
    ]
